# IMPERFECT MARKETS - Introduction of external forces in the supply/demand market 


In [67]:
# import packages

import numpy as np
from IPython.display import Image


# Taxation 

Economic efficiency is the idea that it is impossible to improve the situation of one party without imposing a cost on another.

When taxes are imposed in the market, this has an impact on the supply-demand equilibrium (efficient price and quantity)
Taxation influences economic behaviour and distribution of resources such as the demand or supply of a product. 
Buyers and sellers share the burden depending on elasticity of demand/surply This project seeks cover the following.



* Government imposed taxes 
 * It does not matter which side of the market the tax is legally applied, the economic result would hold as long as the total amount of tax is the same.
* Government Subsideceis 
* price floors
* price ceiling 

This system takes in the variables of the demand and supply curves 

* Consumer surplus is the gap between the price that consumers are willing to pay—based on their preferences—and the market equilibrium price.
* Producer surplus is the gap between the price for which producers are willing to sell a product—based on their costs—and the market equilibrium price.
* Social surplus is the sum of consumer surplus and producer surplus. Total surplus is larger at the equilibrium quantity and price than it will be at any other quantity and price.
* Deadweight loss is loss in total surplus that occurs when the economy produces at an inefficient quantity.


![](taxes-.jpg)

In [68]:
# prompt user to enter variables of the demand supply equations. These are then converted to arrays containing the 
# intercept and Price and quantity variables 
# prints arrays containing this data

d_intercept=float(input("enter demand curve intercept: "))
d_slope=float(input("enter demand curve slope: "))

s_intercept=float(input("enter supply curve intercept: "))
s_slope=float(input("enter supply curve slope: "))

tax_val=float(input("tax amount imposed on supplier: $ "))

P_variables= [1,1]
intercept_variables=[d_intercept,s_intercept]
Q_variables=[d_slope,s_slope]
Q_variables=[ -x for x in Q_variables]
demand_array=[1,Q_variables[0]]
supply_array=[1,Q_variables[1]]
array1=np.array([demand_array,supply_array])
array2=np.array(intercept_variables)

print("variable array: \n {}".format(array1))
print("intercept array: \n {}".format(array2))


enter demand curve intercept: 100
enter demand curve slope: -0.01
enter supply curve intercept: 0
enter supply curve slope: 0.01
tax amount imposed on supplier: $ 60
variable array: 
 [[ 1.    0.01]
 [ 1.   -0.01]]
intercept array: 
 [100.   0.]


In [70]:
# Solves for the efficient equilibrium value of price and quantity at a point where supply= demand in the absense of 
# external market forces such as taxes. 
# solves the producer and consumer surplus in these conditions 

efficient_solution = np.linalg.solve(array1,array2)
print("efficicient price:$ {}".format(efficient_solution[0]))
print("efficicient quantity: {}".format(efficient_solution[1]))
consumer_surplus=0.5*abs(intercept_variables[0]-efficient_solution[0])*efficient_solution[1]
producer_surplus =0.5*abs(intercept_variables[1]-efficient_solution[0])*efficient_solution[1]
print("consumer suplus:$ {}".format(consumer_surplus))
print("producer surplus:$ {}".format(producer_surplus))

efficicient price:$ 50.0
efficicient quantity: 5000.0
consumer suplus:$ 125000.0
producer surplus:$ 125000.0


In [71]:
# makes adjustments in the arrays to account for the tax imposed.

new_s_intercept=tax_val+s_intercept
new_s_intercept
array3=np.array([d_intercept,new_s_intercept])
array3

array([100.,  60.])

In [25]:
# gives a solution to the new equlibrium with the tax imposed. The consumer and producer prices are different as a 
# result and the quantity sold in the market changes 

tax_solution = np.linalg.solve(array1,array3)
producer_price=s_slope*tax_solution[1]+s_intercept
print('new solution: \nConsumer price:$ {}'.format(tax_solution[0]))
print('Consumer quantity sold: {}'.format(tax_solution[1]))
print('price received by producer :$ {}'.format(producer_price))

new solution: 
Consumer price:$ 80.0
Consumer quantity sold: 2000.0
price received by producer :$ 20.0


In [12]:
# solutions to all the changes due to taxes. 

Goverment_tax_revenue= abs(tax_solution[1]-0)*abs(tax_solution[0]-producer_price)

producer_surplus= (1/2)*abs(intercept_variables[1]-producer_price)*tax_solution[1]
producer_tax_incidence=abs(efficient_solution[0]-producer_price)*tax_solution[1]

consumer_surplus= 1/2*abs(intercept_variables[0]-tax_solution[0])*tax_solution[1]
consumer_tax_incidence=abs(efficient_solution[0]-tax_solution[0])*tax_solution[1]

deadweight_loss=1/2*abs(tax_solution[0]-producer_price)*abs(efficient_solution[1]-tax_solution[1])

print('Goverment_tax_revenue:$ {:.2f} \n '.format(Goverment_tax_revenue))
print('new producer_surplus:$ {:.2f}'.format(producer_surplus))
print('producer_tax_incidence:$ {:.2f} \n '.format(producer_tax_incidence))
print('new consumer_surplus:$ {:.2f}'.format(consumer_surplus))
print('consumer_tax_incidence:$ {:.2f} \n '.format(consumer_tax_incidence))
print('deadweight_loss:$ {:.2f}'.format(deadweight_loss))


Goverment_tax_revenue:$ 120000.00 
 
new producer_surplus:$ 20000.00
producer_tax_incidence:$ 60000.00 
 
new consumer_surplus:$ 20000.00
consumer_tax_incidence:$ 60000.00 
 
deadweight_loss:$ 90000.00


## price floor 

A price floor is the lowest legal price a product can be sold at. Price floors are often used by the government to prevent prices of products from being too low. It is often used in the labour market (minimum wage). This leads to  an inefficient market equilibrium. The demand at the floor price is lower than the supply at this proce. As with the case below, the goverment can abosorp the difference between what is demanded and what is supplied in the market. There is the social loss, deadweight loss as well. 
![](price-floor_1_.jpg)

In [32]:
# prompt user to enter variables of the demand supply equations. These are then converted to arrays containing the 
# intercept and Price and quantity variables 
# prints arrays containing this data

d_intercept=float(input(" enter demand curve intercept: "))
d_slope=float(input(" enter demand curve slope: "))

s_intercept=float(input(" enter supply curve intercept: "))
s_slope=float(input(" enter supply curve slope: "))

floor_price=float(input(" enter floor_price: "))

 enter demand curve intercept: 100
 enter demand curve slope: -0.01
 enter supply curve intercept: 0
 enter supply curve slope: 0.01
 enter floor_price: 60


In [34]:
# Solves for the efficient equilibrium value of price and quantity at a point where supply= demand the absence
# of external market factors such as taxes abnd price floors

P_variables= [1,1]
intercept_variables=[d_intercept,s_intercept]
Q_variables=[d_slope,s_slope]
Q_variables=[ -x for x in Q_variables]
demand_array=[1,Q_variables[0]]
supply_array=[1,Q_variables[1]]
array1=np.array([demand_array,supply_array])
array2=np.array(intercept_variables)

print("variable array: \n {}".format(array1))
print("intercept array: \n \n {}".format(array2))

efficient_solution = np.linalg.solve(array1,array2)
print("efficicient price,quantity:{}".format(efficient_solution))


variable array: 
 [[ 1.    0.01]
 [ 1.   -0.01]]
intercept array: 
 
 [100.   0.]
efficicient price,quantity:[  50. 5000.]


In [42]:
#calculating the new inefficient equilibrium . Calculating the consumer surplus, producer surplus and deadweight loss 
#of the market with the imposed price floor.
demand_new_Q=(floor_price-intercept_variables[0])/(-Q_variables[0])
supply_new_Q=(floor_price-intercept_variables[1])/(-Q_variables[1])
surplus=abs(demand_new_Q-supply_new_Q)

consumer_surplus= (1/2)*demand_new_Q*abs(intercept_variables[0]-floor_price)

# interim supply price is the price producers would charge for the corresponding demand quantity of the price ceiling, 
# if this demand quantity wasn't due to price floor 

interim_supply_price=(demand_new_Q*(-Q_variables[1]))+intercept_variables[1]

producer_surplus=0.5*demand_new_Q*(floor_price+(floor_price-interim_supply_price))

deadweight_loss=0.5*(efficient_solution[1]-demand_new_Q)*(floor_price-interim_supply_price)

print ('demand quantity: {}'.format(demand_new_Q))
print('supply quantity: {}'.format(supply_new_Q))
print("surplus supply abosrbed by the government: {} \n\n".format(surplus))
print('consumer surplus:$ {}'.format(consumer_surplus))
print('producer surplus:$ {}'.format(producer_surplus))
print('deadweight loss:$ {}'.format(deadweight_loss))


demand quantity: 4000.0
supply quantity: 6000.0
surplus supply abosrbed by the government: 2000.0 


consumer surplus:$ 80000.0
producer surplus:$ 160000.0
deadweight loss:$ 10000.0


## price ceiling 

A price ceiling is the opposite of a price floor. It is an imposed price control, or limit, on how high a price is charged for a product. Governments use price ceilings to protect consumers from conditions that could make products/services prohibitively expensive.
![](price_ceiling.png)

In [43]:
# prompt user to enter variables of the demand supply equations. These are then converted to arrays containing the 
# intercept and Price and quantity variables 
# prints arrays containing this data

d_intercept=float(input(" enter demand curve intercept: "))
d_slope=float(input("enter demand curve slope: "))

s_intercept=float(input(" enter supply curve intercept: "))
s_slope=float(input(" enter supply curve slope: "))

price_ceiling=float(input(" enter floor_price:$ "))

 enter demand curve intercept: 100
enter demand curve slope: -0.01
 enter supply curve intercept: 0
 enter supply curve slope: 0.01
 enter floor_price:$ 20


In [44]:
# Solves for the efficient equilibrium value of price and quantity at a point where supply= demand the absence
# of external market factors such as taxes abnd price ceilings 


efficient_solution = np.linalg.solve(array1,array2)
print("efficicient price,quantity:{}".format(efficient_solution))


efficicient price,quantity:[  50. 5000.]


In [59]:
# calculating the new inefficient equilibrium . Calculating the consumer surplus, producer surplus and deadweight loss 
# of the market with the imposed price floor.
# at the same price, demand would have been=(price_ceiling-intercept_variables[0])/(-Q_variables[0]) 

supply_new_Q=(price_ceiling-intercept_variables[1])/(-Q_variables[1])
#surplus=abs(demand_new_Q-supply_new_Q)

producer_surplus= 0.5*supply_new_Q*price_ceiling

#interim consumer price is the price producers would charge for the corresponding demand quantity of the price ceiling, 
#if this demand quantity wasn't due to price floor 
interim_consumer_price=(supply_new_Q*(-Q_variables[0]))+intercept_variables[0]

consumer_surplus=0.5*supply_new_Q*(abs(intercept_variables[0]-price_ceiling)+abs(price_ceiling-interim_consumer_price))

deadweight_loss=0.5*abs(efficient_solution[1]-supply_new_Q)*abs(price_ceiling-interim_consumer_price)

print ('demand quantity: {}'.format(demand_new_Q))
print('supply quantity: {}\n'.format(supply_new_Q))
print('consumer surplus: {}'.format(consumer_surplus))
print('producer surplus: {}'.format(producer_surplus))
print('deadweight loss: {}'.format(deadweight_loss))



demand quantity: 8000.0
supply quantity: 2000.0

consumer surplus: 140000.0
producer surplus: 20000.0
deadweight loss: 90000.0
